# Generated by Django 5.1.5 on 2025-01-26 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
    ]
