# Generated by Django 5.1.5 on 2025-01-28 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_extra_data_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.JSONField(default=dict)),
                ('start_date', models.CharField(default='', max_length=100)),
                ('end_date', models.CharField(default='', max_length=100)),
                ('shift_data', models.JSONField(default=dict)),
                ('closing_days', models.JSONField(default=dict)),
                ('free_days', models.JSONField(default=dict)),
                ('schedule_data', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
        ),
    ]
