# Generated by Django 5.1.5 on 2025-02-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_import'),
    ]

    operations = [
        migrations.RenameField(
            model_name='import',
            old_name='import_data',
            new_name='data',
        ),
    ]
