# Generated by Django 5.1.5 on 2025-02-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_import_data_import_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='import_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='F', max_length=10),
        ),
    ]
